@echo off
echo Starting Backend...
start "Backend" cmd /k "cd backend && call .venv\Scripts\activate.bat && python main.py"

echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && bun run dev"

echo Waiting for servers to initialize...
timeout /t 5 /nobreak

echo Opening application in default browser...
start http://localhost:5173
